Repository Popping-community/Popping-Server, pull requests merged in 2025-05, with the labels that each got.

#18 AWS EC2 + Docker 를 통한 CI/CD 파이프라인 구축
  .github/workflows/build.yml
  .gitignore
  .idea/misc.xml
  build.gradle
  src/main/resources/application.properties
  src/main/resources/templates/index.html
Labels: chore

#21 Session을 사용한 로그인 기능 구현
  build.gradle
  src/main/java/com/example/popping/config/AppConfig.java
  src/main/java/com/example/popping/config/SecurityConfig.java
  src/main/java/com/example/popping/constant/SessionConst.java
  src/main/java/com/example/popping/controller/HomeController.java
  src/main/java/com/example/popping/controller/LoginController.java
  src/main/java/com/example/popping/controller/UserController.java
  src/main/java/com/example/popping/domain/User.java
  src/main/java/com/example/popping/domain/UserRole.java
  src/main/java/com/example/popping/dto/JoinRequest.java
  src/main/java/com/example/popping/dto/LoginRequest.java
  src/main/java/com/example/popping/repository/UserRepository.java
  src/main/java/com/example/popping/service/LoginService.java
Labels: feat, chore

#22 로그인 화면 구현
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/loginHome.html
  src/main/resources/templates/users/joinForm.html
Labels: feat

#24 소나큐브, 배포과정 오류 해결
  .github/workflows/build.yml
  build.gradle
  src/main/java/com/example/popping/controller/HomeController.java
Labels: fix

#26 로그인 코드 리팩토링
  .gitattributes
  .github/workflows/build.yml
  .idea/.gitignore
  .idea/Popping-Server.iml
  .idea/misc.xml
  README.md
  plan.md
  pom.xml
  src/main/java/com/example/popping/config/SecurityConfig.java
  src/main/java/com/example/popping/constant/SessionConst.java
  src/main/java/com/example/popping/controller/HomeController.java
  src/main/java/com/example/popping/controller/LoginController.java
  src/main/java/com/example/popping/controller/UserController.java
  src/main/java/com/example/popping/domain/User.java
  src/main/java/com/example/popping/dto/JoinRequest.java
  src/main/java/com/example/popping/dto/LoginRequest.java
  src/main/java/com/example/popping/repository/UserRepository.java
  src/main/java/com/example/popping/service/LoginService.java
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/loginHome.html
  src/main/resources/templates/users/joinForm.html
  src/test/java/com/example/popping/PoppingApplicationTests.java
  study_seok/Spring 1차 공부.md
Labels: refactor

#29 게시판, 게시글 기능 구현
  src/main/java/com/example/popping/PoppingApplication.java
  src/main/java/com/example/popping/controller/BoardController.java
  src/main/java/com/example/popping/controller/LoginController.java
  src/main/java/com/example/popping/controller/PostController.java
  src/main/java/com/example/popping/domain/BaseEntity.java
  src/main/java/com/example/popping/domain/Board.java
  src/main/java/com/example/popping/domain/Post.java
  src/main/java/com/example/popping/domain/User.java
  src/main/java/com/example/popping/dto/BoardCreateRequest.java
  src/main/java/com/example/popping/dto/BoardResponse.java
  src/main/java/com/example/popping/dto/BoardUpdateRequest.java
  src/main/java/com/example/popping/dto/JoinRequest.java
  src/main/java/com/example/popping/dto/PostCreateRequest.java
  src/main/java/com/example/popping/dto/PostResponse.java
  src/main/java/com/example/popping/dto/PostUpdateRequest.java
  src/main/java/com/example/popping/repository/BoardRepository.java
  src/main/java/com/example/popping/repository/PostRepository.java
  src/main/java/com/example/popping/service/BoardService.java
  src/main/java/com/example/popping/service/LoginService.java
  src/main/java/com/example/popping/service/PostService.java
Labels: feat

#30 게시판, 게시글 화면 구현
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit-form.html
  src/main/resources/templates/board/form.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/post/detail.html
  src/main/resources/templates/post/edit-form.html
  src/main/resources/templates/post/form.html
Labels: feat

#32 메인 페이지 수정
  src/main/resources/templates/home.html
  src/main/resources/templates/loginHome.html
Labels: fix

#34 게시글, 게시판 코드 리팩터링
  src/main/java/com/example/popping/controller/BoardController.java
  src/main/java/com/example/popping/controller/LoginController.java
  src/main/java/com/example/popping/controller/PostController.java
  src/main/java/com/example/popping/controller/UserController.java
  src/main/java/com/example/popping/domain/BaseEntity.java
  src/main/java/com/example/popping/domain/Board.java
  src/main/java/com/example/popping/domain/Post.java
  src/main/java/com/example/popping/domain/User.java
  src/main/java/com/example/popping/dto/BoardCreateRequest.java
  src/main/java/com/example/popping/dto/BoardResponse.java
  src/main/java/com/example/popping/dto/JoinRequest.java
  src/main/java/com/example/popping/dto/PostCreateRequest.java
  src/main/java/com/example/popping/dto/PostResponse.java
  src/main/java/com/example/popping/dto/PostUpdateRequest.java
  src/main/java/com/example/popping/repository/BoardRepository.java
  src/main/java/com/example/popping/repository/PostRepository.java
  src/main/java/com/example/popping/service/BoardService.java
  src/main/java/com/example/popping/service/LoginService.java
  src/main/java/com/example/popping/service/PostService.java
Labels: refactor

#37 게시글, 게시판 작성자만 수정/삭제 가능하도록 권한 처리
  src/main/java/com/example/popping/controller/BoardController.java
  src/main/java/com/example/popping/controller/PostController.java
  src/main/java/com/example/popping/domain/User.java
  src/main/java/com/example/popping/dto/BoardResponse.java
  src/main/java/com/example/popping/dto/PostResponse.java
  src/main/java/com/example/popping/exception/GlobalExceptionHandler.java
  src/main/java/com/example/popping/service/BoardService.java
  src/main/java/com/example/popping/service/PostService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/post/detail.html
Labels: feat

#41 Spring Security 기반 인증/인가 시스템 도입
  build.gradle
  src/main/java/com/example/popping/config/AppConfig.java
  src/main/java/com/example/popping/config/SecurityConfig.java
  src/main/java/com/example/popping/controller/BoardController.java
  src/main/java/com/example/popping/controller/HomeController.java
  src/main/java/com/example/popping/controller/LoginController.java
  src/main/java/com/example/popping/controller/PostController.java
  src/main/java/com/example/popping/controller/UserController.java
  src/main/java/com/example/popping/domain/UserPrincipal.java
  src/main/java/com/example/popping/service/BoardService.java
  src/main/java/com/example/popping/service/CustomUserDetailsService.java
  src/main/java/com/example/popping/service/PostService.java
  src/main/java/com/example/popping/service/UserService.java
Labels: feat

#42 뷰 템플릿에서 로그인 여부에 따라 버튼 노출 처리
  .idea/misc.xml
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit-form.html
  src/main/resources/templates/board/form.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/loginHome.html
  src/main/resources/templates/post/delete-password-form.html
  src/main/resources/templates/post/detail.html
  src/main/resources/templates/post/edit-form.html
  src/main/resources/templates/post/edit-password-form.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/users/joinForm.html
Labels: feat

#46 게시글 상세 페이지에 댓글 및 답글 추가
  src/main/resources/templates/post/detail.html
Labels: feat
