Repository Popping-community/Popping-Server, pull requests merged in 2025-03, with the labels that each got.

#2 깃허브 세팅
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
Labels: chore

#4 readme 작성
  README.md
Labels: docs

#6 프로젝트 계획 및 화면기획
  image/coment.png
  image/detail.png
  image/login.png
  image/main.png
  image/post.png
  image/signin.png
  plan.md
Labels: docs

#8 프로젝트 세팅 및 소나큐브 적용
  .gitattributes
  .github/workflows/build.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  naver-checkstyle-suppressions.xml
  naver-checkstyle.xml
  settings.gradle
  src/main/java/com/example/popping/PoppingApplication.java
  src/main/resources/application.properties
  src/test/java/com/example/popping/PoppingApplicationTests.java
Labels: chore

#11 깃허브 액션 오류 해결
  .github/workflows/build.yml
  build.gradle
Labels: fix
